---

jobs:

- name: reconfigure
  serial: true
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
    - get: secrets
      # Remember to manually trigger a new build if you upload a new version
      # of the credentials file.
      trigger: false
    - get: tooling-terraform-state-yaml
      resource: tooling-terraform-state-yaml
      trigger: true
  - set_pipeline: ((name))
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml
    - tooling-terraform-state-yaml/state.yml

- name: update-cvd
  plan:
  - get: cvd-database-s3
  - get: cvd-meta-s3
  - get: twice-daily
    trigger: true
  - get: src
  - get: general-task
  - task: update-definitions
    image: general-task
    config:
      platform: linux
      params:
        STATE_FILE: cvd-meta-s3/state.json
        DATABASE_DIRECTORY: cvd-database-s3
      inputs:
      - name: cvd-database-s3
      - name: cvd-meta-s3
      - name: src
      outputs:
      - name: cvd-database-s3
      - name: cvd-meta-s3
      - name: src
      run:
        path: src/ci/update-definitions.sh
  - put: cvd-meta-s3
    inputs:
    - cvd-meta-s3
  - put: cvd-database-s3
    inputs:
    - cvd-database-s3


############################
#  RESOURCES

resources:

# the meta bucket stores logs, config, and state files
# the state file is _probably_ all we need to track
# this is private data
- name: cvd-meta-s3
  type: s3-simple
  source:
    region: ((cvd-meta-bucket-region))
    bucket: ((cvd-meta-bucket-name))
    access_key_id: ((terraform_outputs.cvd_sync_access_key_id_curr))
    secret_access_key:  ((terraform_outputs.cvd_sync_secret_access_key_curr))
    change_dir_to: cvd-meta-s3
    options:
    - "--sse AES256"

# the database bucket stores the virus definition database files
# these are served publicly
- name: cvd-database-s3
  type: s3-simple
  source:
    region: ((cvd-database-bucket-region))
    bucket: ((cvd-database-bucket-name))
    access_key_id: ((terraform_outputs.cvd_sync_access_key_id_curr))
    secret_access_key:  ((terraform_outputs.cvd_sync_secret_access_key_curr))
    change_dir_to: cvd-database-s3
    options:
    - "--sse AES256"

- name: src
  type: git
  icon: github-circle
  check_every: 10s
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: twice-daily
  type: time
  source:
    interval: 12h

 - name: general-task
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: general-task
      aws_region: us-gov-west-1
      tag: latest

- name: secrets
  type: s3-iam
  icon: cloud-lock
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: tooling-terraform-state-yaml
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file))
    region_name: ((aws-region))


############################
#  RESOURCE TYPES

resource_types:
- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest

- name: s3-simple
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: s3-simple-resource
    aws_region: us-gov-west-1
    tag: latest

- name: s3-iam
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: s3-resource
    aws_region: us-gov-west-1
    tag: latest

- name: time
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: time-resource
    aws_region: us-gov-west-1
    tag: latest

- name: git
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: git-resource
    aws_region: us-gov-west-1
    tag: latest
