---

jobs:

- name: reconfigure
  serial: true
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
  - get: secrets
    # Remember to manually trigger a new build if you upload a new version
    # of the credentials file.
    trigger: false
  - get: tooling-terraform-state-yaml
  - set_pipeline: ((name))
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml
    - tooling-terraform-state-yaml/state.yml

- name: update-cvdupdate-image
  plan:
  - get: src
    trigger: true
  - put: cvdupdate-image
    params:
      build: src/docker

- name: update-cvd
  plan:
  - get: cvd-database-s3
  - get: cvd-meta-s3
  - get: twice-daily
    trigger: true
  - get: src
  - get: cvdupdate-image
  - task: update-definitions
    image: cvdupdate-image
    config:
      platform: linux
      params:
        STATE_FILE: cvd-meta-s3/state.json
        DATABASE_DIRECTORY: cvd-database-s3
      inputs:
      - name: cvd-database-s3
      - name: cvd-meta-s3
      - name: src
      outputs:
      - name: cvd-database-s3
      - name: cvd-meta-s3
      - name: src
      run: 
        path: src/ci/update-definitions.sh
  - put: cvd-meta-s3
    inputs:
    - cvd-meta-s3
  - put: cvd-database-s3
    inputs:
    - cvd-database-s3


############################
#  RESOURCES

resources:

# the meta bucket stores logs, config, and state files
# the state file is _probably_ all we need to track
# this is private data
- name: cvd-meta-s3
  type: s3-simple
  source:
    region: ((cvd-meta-bucket-region))
    bucket: ((cvd-meta-bucket-name))
    access_key_id: ((terraform_outputs.cvd_sync_access_key_id_curr))
    secret_access_key:  ((terraform_outputs.cvd_sync_secret_access_key_curr))
    change_dir_to: cvd-meta-s3
    options:
    - "--sse AES256"

# the database bucket stores the virus definition database files
# these are served publicly
- name: cvd-database-s3
  type: s3-simple
  source:
    region: ((cvd-database-bucket-region))
    bucket: ((cvd-database-bucket-name))
    access_key_id: ((terraform_outputs.cvd_sync_access_key_id_curr))
    secret_access_key:  ((terraform_outputs.cvd_sync_secret_access_key_curr))
    change_dir_to: cvd-database-s3
    options:
    - "--sse AES256"

- name: src
  type: git
  icon: github-circle
  check_every: 10s
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: twice-daily
  type: time
  source:
    interval: 12h

- name: cvdupdate-image
  type: docker-image
  icon: docker
  source:
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-image))

- name: secrets
  type: s3-iam
  icon: cloud-lock
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: tooling-terraform-state-yaml
  type: s3-iam
  tags: [iaas]
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file))
    region_name: ((aws-region))


############################
#  RESOURCE TYPES

resource_types:

- name: s3-simple
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource

